name = "Quick Reaction Force Spawner"
prefix = "qrfs"
author = "CryptikLemur"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3
exclude = ["bin"]
modname = "{{prefix}}"
files = [
    "mod.cpp",
    "logo.paa"
]